### ISSUE TITLE
Unable to run project on browser

### ISSUE THREAD

**Issue by minoush82** [raju2592/derivative-calculator#1]
After running the node app (through `node bin/www`), I get the following error in the browser's console: `Uncaught ReferenceError: require is not defined at input.js:2:24`. I tried multiple fixes suggested online e.g. including the library require.js in index.html, adding  {"type": "module"} to package.json, etc. but none worked. Any ideas?

**Comment by raju2592** [comment]
Perviously, the app was a backend nodejs app and the `input.js` file was calling the backend apis to fetch the result. Currently, the whole app runs on the frontend. This requires the project to be build using a module bundler. The project is currently using `parcel`. To run, simply use `npm start`.

**Comment by minoush82** [comment]
Perfect! Thanks a lot.
